name: Update bilder.json

on:
  push:
    paths:
      - 'images/**'
  schedule:
    - cron: '0 * * * *' # stündlich

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: .  # <-- Stelle sicher, dass dies auf Root zeigt

      - name: Run update_bilder.js
        run: node update_bilder.js
        working-directory: .  # <-- wichtig: Root-Verzeichnis verwenden

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🔄 Auto-update bilder.json
          file_pattern: data/bilder.json
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
