name: Bilderliste aktualisieren

on:
  push:
    paths:
      - 'images/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v4

      - name: Node.js Umgebung vorbereiten
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: JSON-Datei erzeugen
        run: |
          echo "{" > bilder.json
          echo '  "bilder": [' >> bilder.json
          find images -type f \( -iname 'basajaun*.jpg' -o -iname 'basajaun*.jpeg' -o -iname 'basajaun*.png' -o -iname 'basajaun*.webp' \) | sed 's|images/||' | sort | sed 's/^/    "/;s/$/",/' >> bilder.json
          sed -i '$ s/,$//' bilder.json
          echo '  ],' >> bilder.json
          echo '  "updated": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"' >> bilder.json
          echo "}" >> bilder.json

      - name: Änderungen committen
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Bilderliste aktualisiert (Root-Version)'
          file_pattern: bilder.json
